### ISSUE TITLE
{'login': {'result': 'Deprecated', 'wait': 1}}

### ISSUE THREAD

**Issue by jacobMschiller** [djhenderson/pywikitree#3]
Not sure why this error is popping up. I checked my secrets.py file and the username and password are both correct. I used the below code to check everything would be working smoothly, and I can't run getPersonFSConnections("<my WikiTree ID>").

r = apps.login(WT_USER, WT_PASS)
j = r.json()
pp.pprint(j)

**Comment by djhenderson** [comment]
There have been a number of breaking changes in the WikiTree API, which has broken this package. To date, I have not been able to bring it back to operational status.
